import shape
shape.coords(-50,-50)
shape.beginfill('black')
shape.rect(150,300)
shape.endfill()
shape.coords(27,150)
shape.beginfill('red')
shape.circle(30)
shape.endfill()
shape.coords(27,70)
shape.beginfill('Yellow')
shape.circle(30)
shape.endfill()
shape.coords(27,-5)
shape.beginfill('Green')
shape.circle(30)
shape.endfill()
shape.done()
