import shape
from random import randint
shape.speed(0)
shape.coords(-320,220)
shape.beginfill('yellow')
shape.square(50)
shape.endfill()
shape.coords(-320,150)
shape.beginfill('green')
shape.square(50)
shape.endfill()
shape.coords(-320,80)
shape.beginfill('pink')
shape.square(50)
shape.endfill()
shape.coords(-320,10)
shape.beginfill('Maroon')
shape.square(50)
shape.endfill()
shape.coords(-250,220)
shape.beginfill('red')
shape.square(50)
shape.endfill()
shape.coords(-250,150)
shape.beginfill('Olive')
shape.square(50)
shape.endfill()
while 1:
    shape.coords(randint(-340,340),randint(-340,340))
    shape.beginfill('white')
    shape.square(-100)
    shape.endfill()
    shape.beginfill('Silver')
    shape.rect(-100,20)
    shape.endfill()
shape.done()


